import React from 'react';
import { Printer, Download, BarChart3, ShieldAlert, Award, FileText, CheckCircle2 } from 'lucide-react';

export const PerformanceReportPage = () => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div style={{ maxWidth: '1100px', margin: '0 auto', padding: '2rem 1.5rem 5rem' }} className="animate-fade-in">
      
      {/* Header */}
      <div className="handcrafted-card" style={{ padding: '2rem 2.2rem', marginBottom: '2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <span style={{ fontSize: '0.78rem', color: '#38bdf8', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '1px' }}>
            Executive AI Analytics
          </span>
          <h1 style={{ fontSize: '2.2rem', fontWeight: 800, color: '#f9fafb', margin: '4px 0 0' }}>
            Performance & Risk Summary Report
          </h1>
          <p style={{ color: '#9ca3af', fontSize: '0.92rem' }}>
            Institutional Evaluation Report • Generated by AI Intelligence Engine
          </p>
        </div>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button onClick={handlePrint} className="btn-handcrafted btn-primary-glow" style={{ borderRadius: '12px' }}>
            <Printer size={18} /> Print Official Report
          </button>
        </div>
      </div>

      {/* Report Document Box */}
      <div className="handcrafted-card" style={{ padding: '2.5rem', background: '#111827', border: '1px solid rgba(255,255,255,0.1)' }}>
        
        {/* Official Letterhead */}
        <div style={{ borderBottom: '2px solid rgba(255,255,255,0.1)', paddingBottom: '1.5rem', marginBottom: '2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 900, color: '#ffffff' }}>EduSmart AI Microservice Portal</h2>
            <p style={{ color: '#9ca3af', fontSize: '0.88rem' }}>Institutional Academic Risk & Performance Report</p>
          </div>
          <div style={{ textAlign: 'right', fontSize: '0.85rem', color: '#9ca3af' }}>
            <div>Date: <strong>August 16, 2026</strong></div>
            <div>Report ID: <strong style={{ color: '#38bdf8' }}>RPT-2026-8492</strong></div>
          </div>
        </div>

        {/* Executive Summary */}
        <div style={{ marginBottom: '2rem' }}>
          <h3 style={{ fontSize: '1.2rem', fontWeight: 800, color: '#ffffff', marginBottom: '0.8rem' }}>Executive Summary</h3>
          <p style={{ color: '#cbd5e1', fontSize: '0.95rem', lineHeight: '1.6' }}>
            This comprehensive report synthesizes student performance data across internal midterms, assignment submissions, and attendance logs processed by the Python FastAPI Machine Learning service. The analysis identifies key performance metrics, flags at-risk students, and outlines targeted remedial actions.
          </p>
        </div>

        {/* Risk Level Distribution */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1.2rem', marginBottom: '2.5rem' }}>
          <div style={{ background: 'rgba(16,185,129,0.1)', padding: '1.2rem', borderRadius: '12px', border: '1px solid rgba(16,185,129,0.3)' }}>
            <div style={{ fontSize: '0.8rem', color: '#34d399', fontWeight: 800, textTransform: 'uppercase' }}>LOW RISK STUDENTS</div>
            <div style={{ fontSize: '2.2rem', fontWeight: 900, color: '#34d399', margin: '4px 0' }}>85.2%</div>
            <div style={{ fontSize: '0.8rem', color: '#9ca3af' }}>Satisfactory Academic Standing</div>
          </div>

          <div style={{ background: 'rgba(245,158,11,0.1)', padding: '1.2rem', borderRadius: '12px', border: '1px solid rgba(245,158,11,0.3)' }}>
            <div style={{ fontSize: '0.8rem', color: '#fbbf24', fontWeight: 800, textTransform: 'uppercase' }}>MEDIUM RISK STUDENTS</div>
            <div style={{ fontSize: '2.2rem', fontWeight: 900, color: '#fbbf24', margin: '4px 0' }}>10.4%</div>
            <div style={{ fontSize: '0.8rem', color: '#9ca3af' }}>Requires Monitoring</div>
          </div>

          <div style={{ background: 'rgba(244,63,94,0.1)', padding: '1.2rem', borderRadius: '12px', border: '1px solid rgba(244,63,94,0.3)' }}>
            <div style={{ fontSize: '0.8rem', color: '#fb7185', fontWeight: 800, textTransform: 'uppercase' }}>HIGH RISK STUDENTS</div>
            <div style={{ fontSize: '2.2rem', fontWeight: 900, color: '#fb7185', margin: '4px 0' }}>4.4%</div>
            <div style={{ fontSize: '0.8rem', color: '#9ca3af' }}>Urgent Intervention Required</div>
          </div>
        </div>

        {/* Action Recommendations */}
        <div>
          <h3 style={{ fontSize: '1.2rem', fontWeight: 800, color: '#ffffff', marginBottom: '0.8rem' }}>Automated AI Action Directives</h3>
          <ul style={{ color: '#cbd5e1', fontSize: '0.92rem', lineHeight: '1.7', paddingLeft: '1.2rem' }}>
            <li>Conduct mandatory faculty counseling for students with attendance below 75%.</li>
            <li>Schedule weekly peer-assisted tutorial sessions for Operating Systems and Discrete Mathematics.</li>
            <li>Re-assess internal assignment grading rubrics for low-performing cohorts.</li>
          </ul>
        </div>

      </div>

    </div>
  );
};
