import React from 'react';
import { Printer, Download, BarChart3, ShieldAlert, Award, FileText, CheckCircle2, Sparkles } from 'lucide-react';

export const PerformanceReportPage = () => {
  const handlePrint = () => {
    window.print();
  };

  const handleDownloadReport = () => {
    const reportData = {
      institution: "EduSmart AI Portal",
      report_id: "RPT-2026-8492",
      date: "August 16, 2026",
      risk_summary: {
        low_risk_pct: "85.2%",
        medium_risk_pct: "10.4%",
        high_risk_pct: "4.4%"
      },
      ai_action_directives: [
        "Conduct mandatory faculty counseling for students with attendance below 75%.",
        "Schedule weekly peer-assisted tutorial sessions for Operating Systems and Discrete Mathematics.",
        "Re-assess internal assignment grading rubrics for low-performing cohorts."
      ]
    };

    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AI_Institutional_Performance_Report_${new Date().toISOString().slice(0,10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ maxWidth: '1100px', margin: '0 auto', padding: '2rem 1.5rem 5rem' }} className="animate-fade-in">
      
      {/* Header */}
      <div className="handcrafted-card" style={{ padding: '2rem 2.2rem', marginBottom: '2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem', background: '#ffffff' }}>
        <div>
          <span style={{ fontSize: '0.78rem', color: 'var(--brand-red)', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '1px' }}>
            Executive AI Analytics
          </span>
          <h1 style={{ fontSize: '2.2rem', fontWeight: 800, color: '#0f172a', margin: '4px 0 0' }}>
            Reports & Insights Dashboard
          </h1>
          <p style={{ color: '#64748b', fontSize: '0.92rem' }}>
            Institutional Evaluation Report • Generated by Python AI Intelligence Engine
          </p>
        </div>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button onClick={handleDownloadReport} className="btn-handcrafted btn-primary-glow" style={{ borderRadius: '12px' }}>
            <Download size={18} /> Download AI Report (JSON)
          </button>
          <button onClick={handlePrint} className="btn-handcrafted btn-ghost-glass" style={{ borderRadius: '12px' }}>
            <Printer size={18} /> Print PDF Report
          </button>
        </div>
      </div>

      {/* Report Document Box */}
      <div className="handcrafted-card" style={{ padding: '2.5rem', background: '#ffffff', border: '1px solid #e2e8f0' }}>
        
        {/* Official Letterhead */}
        <div style={{ borderBottom: '2px solid #e2e8f0', paddingBottom: '1.5rem', marginBottom: '2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 900, color: '#0f172a' }}>EduSmart AI Microservice Portal</h2>
            <p style={{ color: '#64748b', fontSize: '0.88rem' }}>Institutional Academic Risk & Performance Report</p>
          </div>
          <div style={{ textAlign: 'right', fontSize: '0.85rem', color: '#64748b' }}>
            <div>Date: <strong>August 16, 2026</strong></div>
            <div>Report ID: <strong style={{ color: 'var(--brand-red)' }}>RPT-2026-8492</strong></div>
          </div>
        </div>

        {/* Executive Summary */}
        <div style={{ marginBottom: '2rem' }}>
          <h3 style={{ fontSize: '1.2rem', fontWeight: 800, color: '#0f172a', marginBottom: '0.8rem' }}>Executive Summary</h3>
          <p style={{ color: '#475569', fontSize: '0.95rem', lineHeight: '1.6' }}>
            This comprehensive report synthesizes student performance data across internal midterms, assignment submissions, and attendance logs processed by the Python FastAPI Machine Learning service. The analysis identifies key performance metrics, flags at-risk students, and outlines targeted remedial actions.
          </p>
        </div>

        {/* Risk Level Distribution */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1.2rem', marginBottom: '2.5rem' }}>
          <div style={{ background: '#ecfdf5', padding: '1.2rem', borderRadius: '12px', border: '1px solid #a7f3d0' }}>
            <div style={{ fontSize: '0.8rem', color: '#047857', fontWeight: 800, textTransform: 'uppercase' }}>LOW RISK STUDENTS</div>
            <div style={{ fontSize: '2.2rem', fontWeight: 900, color: '#059669', margin: '4px 0' }}>85.2%</div>
            <div style={{ fontSize: '0.8rem', color: '#065f46' }}>Satisfactory Academic Standing</div>
          </div>

          <div style={{ background: '#fefce8', padding: '1.2rem', borderRadius: '12px', border: '1px solid #fef08a' }}>
            <div style={{ fontSize: '0.8rem', color: '#b45309', fontWeight: 800, textTransform: 'uppercase' }}>MEDIUM RISK STUDENTS</div>
            <div style={{ fontSize: '2.2rem', fontWeight: 900, color: '#d97706', margin: '4px 0' }}>10.4%</div>
            <div style={{ fontSize: '0.8rem', color: '#92400e' }}>Requires Monitoring</div>
          </div>

          <div style={{ background: '#fff1f2', padding: '1.2rem', borderRadius: '12px', border: '1px solid #fecdd3' }}>
            <div style={{ fontSize: '0.8rem', color: '#be123c', fontWeight: 800, textTransform: 'uppercase' }}>HIGH RISK STUDENTS</div>
            <div style={{ fontSize: '2.2rem', fontWeight: 900, color: '#e11d48', margin: '4px 0' }}>4.4%</div>
            <div style={{ fontSize: '0.8rem', color: '#9f1239' }}>Urgent Intervention Required</div>
          </div>
        </div>

        {/* Action Recommendations */}
        <div>
          <h3 style={{ fontSize: '1.2rem', fontWeight: 800, color: '#0f172a', marginBottom: '0.8rem' }}>Automated AI Action Directives</h3>
          <ul style={{ color: '#475569', fontSize: '0.92rem', lineHeight: '1.7', paddingLeft: '1.2rem' }}>
            <li>Conduct mandatory faculty counseling for students with attendance below 75%.</li>
            <li>Schedule weekly peer-assisted tutorial sessions for Operating Systems and Discrete Mathematics.</li>
            <li>Re-assess internal assignment grading rubrics for low-performing cohorts.</li>
          </ul>
        </div>

      </div>

    </div>
  );
};
